Document: adapterbase
Title: Debian adapterbase Manual
Author: <insert document author here>
Abstract: This manual describes what adapterbase is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/adapterbase/adapterbase.sgml.gz

Format: postscript
Files: /usr/share/doc/adapterbase/adapterbase.ps.gz

Format: text
Files: /usr/share/doc/adapterbase/adapterbase.text.gz

Format: HTML
Index: /usr/share/doc/adapterbase/html/index.html
Files: /usr/share/doc/adapterbase/html/*.html
